import '@/app/globals.css'
import { Toaster } from '@/components/ui/sonner'
import { cn } from '@/lib/utils'
import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import Footer from './_components/footer'
import Header from './_components/header'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head></head>
        <body
          className={cn(
            'min-h-screen bg-background font-sans antialiased flex flex-col',
            fontSans.variable
          )}
        >
          <Toaster richColors />

          <Header />
          <main className="flex-1 space-y-16 flex flex-col">{children}</main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  )
}
